service:
  name: serverless-nodejs-ts
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2
  # environment:
  #   -

functions:
  root:
    handler: src/controllers/index.hello
    events:
      - http:
          method: get
          path: /
